pollapp/pollapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # Endpoints
    path('', views.index, name='index'),
    path('polls/', include('polls.urls')),
]

pollapp/polls/urls.py
from django.contrib import admin
from django.urls import path

from polls import views

app_name = 'polls'

urlpatterns = [
    # polls Endpoints
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.details, name='poll_details'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/results/', views.results, name='results'),

    path('json', views.json_test_handler, name='json_test')
]

pollapp/polls/models.py
import json
import datetime
from django.utils import timezone
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # def __str__(self):
    #     return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    @staticmethod
    def datetime_converter(o):
        if isinstance(o, datetime):
            return o.__str__()
    
    def to_json(self):
        return json.dumps(self.__dict__, default=self.datetime_converter)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

pollapp/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.http import JsonResponse
from django.urls import reverse
# from django.template import loader

from django.core import serializers


from polls.models import Question, Choice

# Create your views here.


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'polls/index.html', context)


def json_test_handler(request):
    return JsonResponse({
            'key1': 'value1',
            'key2': [
                {
                    'key2.1': 'val1',
                },
            ],
            })

def details(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/details.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def details_json(request, question_id):
    try:
        question = Question.objects.get(pk=question_id).values()
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return JsonResponse({"data": list(question)})
    # return JsonResponse({
    #     "question_text": question.question_text,
    #     "pub_date": question.pub_date,
    # })

pollapp/polls/templates/polls/details.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>
<h3>{{ question.pub_date }}</h3>
{% if error_message %}<p><strong style="color: red">{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

pollapp/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:poll_details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

pollapp/polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:poll_details' question.id %}">Vote again?</a>